CREATE TABLE Clientes (
id TEXT PRIMARY KEY NOT NULL UNIQUE,
NomeCompleto TEXT NOT NULL,
DataNascimento INT NOT NULL,
Rg TEXT NOT NULL UNIQUE,
Cpf TEXT NOT NULL UNIQUE,
Endereco TEXT NOT NULL,
Cep TEXT NOT NULL,
Numero INT NOT NULL,
Senha TEXT NOT NULL,
ConfirmarSenha TEXT NOT NULL
);